# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

r_github_packages: hadley/devtools#1263

script:
  - R CMD build .
  - travis_wait 60 R CMD check flipData.tar.gz
 
 notifications:
  slack:
    rooms: 
        - numbers:FTgSTNHC2rpanhJMGTKMwZXM#github-notifications
    template:
      - "Build <%{build_url}|#%{build_number}> %{result} in %{repository_name}@%{branch} by %{author}: <%{compare_url}|%{commit_message}>"
    on_success: change
    on_failure: always
