version: 2.1
orbs:
  r-packages: displayr/r-packages@dev:alpha
parameters:
  trigger-message:
    type: string
    default: ""
  remote-deps:
    type: string
    default: "Displayr/flipDevTools@TEST-347"
  plugins-branch:
    type: string
    default: ""
  triggered-packages:
    type: string
    default: ""
  executor:
    type: enum
    enum: [nightly, rocker, machine, rocker_geo]
    default: nightly
  save-snapshots:
    type: boolean
    default: false

workflows:
  build-and-check-R-package:
    jobs:
      - r-packages/build_and_check_package:
          executor: << pipeline.parameters.executor >>
          name: BuildAndCheckPackage
          context:
            - r_packages
          remote_deps: << pipeline.parameters.remote-deps >>
          separate_test_job: false
          save_snapshots: << pipeline.parameters.save-snapshots >>
          pre-steps:
            - run:
                command: |
                  # Forcibly remove rustup folder. This avoids 'Invalid cross-device link (os error 18)' errors that seem related to Docker's execution environment - failures when moving rustup folders to /tmp/* paths. See:
                  # https://app.circleci.com/pipelines/github/Displayr/flipData/367/workflows/7f20ec95-3031-4fef-a52a-14ac48d54b0b/jobs/673?invite=true#step-102-1945_205
                  rm -rf /.rustup
                  # Install rustup
                  curl https://sh.rustup.rs -sSf | bash -s -- -y
                  # Source rustup into $PATH
                  . "$HOME/.cargo/env"
                  rustup show
                  # Install the current version of Rust toolchain.
                  rustup toolchain install stable
                  rustup default stable
                  rustup show
      - r-packages/deploy_package:
          executor: << pipeline.parameters.executor >>
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          filters:
            branches:
              only:
                - master
      - r-packages/trigger_revdeps:
          executor: << pipeline.parameters.executor >>
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          remote_deps: << pipeline.parameters.remote-deps >>
          plugins_branch: << pipeline.parameters.plugins-branch >>
          trigger_message: << pipeline.parameters.trigger-message >>
          triggered_packages: << pipeline.parameters.triggered-packages >>
