name: Build flipData

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build flipData
    permissions:
      checks: write
      contents: read
    uses: Displayr/nixr-public/.github/workflows/build-flake-installable.yaml@master
    with:
      installable-path: pkgs.x86_64-linux.rPackages.flipData
      build-args: --override-input flipData .
      installable-name: flipData
    secrets: inherit
